### VECTORIZATION

In [1]:
import numpy as np
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [6]:
import time

a=np.random.rand(1000000)
b=np.random.rand(1000000)

tic=time.time()
c=np.dot(a,b)
toc=time.time()

print(c)
print("Vectorized version: "+str(1000*(toc-tic))+"ms")

c=0
tic=time.time()
for i in range(1000000):
    c+=a[i]*b[i]
toc=time.time()

print(c)
print("For loop: "+str(1000*(toc-tic))+"ms")

249801.1008870855
Vectorized version: 8.002519607543945ms
249801.10088708898
For loop: 544.346809387207ms


### BROADCASTING

In [9]:
import numpy as np
A=np.array([[56.0,0.0,4.4,68.0],
          [1.2,104.0,52.0,8.0],
          [1.8,135.0,99.0,0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [10]:
cal =A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [11]:
percentage=100*A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


# Numpy

In [21]:
import numpy as np

a=np.random.randn(5)

In [22]:
print(a)

[-1.00535958  1.17745185 -1.41854428 -0.25263966  0.34810891]


In [23]:
print(a.shape)

(5,)


In [24]:
print(a.T)

[-1.00535958  1.17745185 -1.41854428 -0.25263966  0.34810891]


In [25]:
print(np.dot(a,a.T))

4.594415229069056


In [26]:
a=np.random.randn(5,1)
print(a)

[[-0.45754165]
 [ 0.5299104 ]
 [ 0.88752638]
 [ 0.04431919]
 [ 0.29443506]]


In [27]:
print(a.T)

[[-0.45754165  0.5299104   0.88752638  0.04431919  0.29443506]]


In [28]:
print(np.dot(a,a.T))

[[ 0.20934436 -0.24245608 -0.40608028 -0.02027788 -0.1347163 ]
 [-0.24245608  0.28080503  0.47030945  0.0234852   0.1560242 ]
 [-0.40608028  0.47030945  0.78770308  0.03933445  0.26131888]
 [-0.02027788  0.0234852   0.03933445  0.00196419  0.01304912]
 [-0.1347163   0.1560242   0.26131888  0.01304912  0.08669201]]
